#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'curl'
cookbook 'drupal',
  :github => 'mdxp/drupal-cookbook'
cookbook 'monitor'
cookbook 'drupal-monitor',
  :path => 'cookbooks-source/drupal-monitor'
cookbook 'redis',
  :github => 'miah/chef-redis'
cookbook "vim"
